alias: Tesla PowerWall charging automation
description: "Automations to optimize charging Tesla PowerWall battery and avoid
  importing power during peak utility pricing period."
triggers:
  - trigger: time
    at: "11:00:00"
    id: low_gen_charge_start
  - trigger: time
    at: "13:00:00"
    id: high_gen_charge_start
  - trigger: time
    at: "14:00:00"
    id: low_gen_battery_top_off
  - trigger: time
    at: "15:00:00"
    id: return_to_self_consumption
  - trigger: numeric_state
    entity_id:
      - sensor.my_house_percentage_charged
    below: 10
    id: low_battery
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - low_gen_charge_start
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            below: 25
        sequence:
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_operation_mode
            data:
              option: autonomous
          - action: number.set_value
            metadata: {}
            target:
              entity_id: number.my_house_backup_reserve
            data:
              value: "80"
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: switch.my_house_allow_charging_from_grid
            data: {}
        alias: Low solar generation battery charge start
      - conditions:
          - condition: trigger
            id:
              - high_gen_charge_start
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            above: 24.99
        sequence:
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_operation_mode
            data:
              option: autonomous
          - action: number.set_value
            metadata: {}
            target:
              entity_id: number.my_house_backup_reserve
            data:
              value: "70"
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: switch.my_house_allow_charging_from_grid
            data: {}
        alias: High solar generation battery charge start
      - conditions:
          - condition: trigger
            id:
              - low_gen_battery_top_off
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            below: 25
        sequence:
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_operation_mode
            data:
              option: backup
          - action: number.set_value
            metadata: {}
            target:
              entity_id: number.my_house_backup_reserve
            data:
              value: "100"
          - action: switch.turn_on
            metadata: {}
            target:
              entity_id: switch.my_house_allow_charging_from_grid
            data: {}
        alias: Low solar generation battery charge top off
      - conditions:
          - condition: trigger
            id:
              - return_to_self_consumption
        sequence:
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_operation_mode
            data:
              option: self_consumption
          - action: number.set_value
            metadata: {}
            target:
              entity_id: number.my_house_backup_reserve
            data:
              value: "10"
          - action: switch.turn_off
            metadata: {}
            target:
              entity_id: switch.my_house_allow_charging_from_grid
            data: {}
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_allow_export
            data:
              option: pv_only
        alias: Return to self-consumption mode
      - conditions:
          - condition: trigger
            id:
              - low_battery
        sequence:
          - action: select.select_option
            metadata: {}
            target:
              entity_id: select.my_house_operation_mode
            data:
              option: autonomous
        alias: Draw from grid if battery hits lower charge percentage threshold
mode: single
